services:
  unilidar:
    image: ghcr.io/cueltschey/parkme-uinlidar 

    build:
      context: lidar
      dockerfile: Dockerfile

    volumes:
      - ./data_files:/data

    ports:
      - 9002:9002

    env_file:
      - .env
    networks:
      pointcloud:
        ipv4_address: 172.26.1.7
    configs:
      - unilidar.yml
    command: parkme_unilidar -c /unilidar.yml

  classifier:
    image: ghcr.io/cueltschey/parkme-classifier

    build:
      context: classifier
      dockerfile: Dockerfile

    ports:
      - 9003:9003

    environment:
      LIDAR_WS_URL: ws://unilidar:9002
      CLASSIFIER_PORT: 9003

    depends_on:
      - unilidar

    networks:
      pointcloud:
        ipv4_address: 172.26.1.9

  renderer:
    image: ghcr.io/cueltschey/parkme-renderer

    build:
      context: renderer
      dockerfile: Dockerfile

    ports:
      - 8080:8080

    env_file:
      - .env
    networks:
      pointcloud:
        ipv4_address: 172.26.1.8




configs:
  unilidar.yml:
    file: ${UNILIDAR_CONFIG:-configs/replay.yaml}

networks:
  default:
    driver: bridge

  pointcloud:
    name: parkme_pointcloud
    ipam:
      driver: default
      config:
        - subnet: 172.26.1.0/24
