services:
  unilidar:
    image: ghcr.io/cueltschey/parkme-uinlidar 

    build:
      context: lidar
      dockerfile: Dockerfile

    volumes:
      - ./data_files:/data

    ports:
      - 9002:9002

    env_file:
      - .env
    networks:
      pointcloud:
        ipv4_address: 172.26.1.7
    configs:
      - unilidar.yml
    command: parkme_unilidar -c /unilidar.yml

  classifier:
    image: ghcr.io/cueltschey/parkme-classifier

    build:
      context: classifier
      dockerfile: Dockerfile

    ports:
      - 9003:9003

    environment:
      LIDAR_WS_URL: ws://unilidar:9002
      CLASSIFIER_PORT: 9003

    env_file:
      - .env

    depends_on:
      - unilidar
      - influxdb

    networks:
      pointcloud:
        ipv4_address: 172.26.1.9
      metrics:
         ipv4_address: 172.19.1.7

  renderer:
    image: ghcr.io/cueltschey/parkme-renderer

    build:
      context: renderer
      dockerfile: Dockerfile

    ports:
      - 8080:8080

    env_file:
      - .env
    networks:
      pointcloud:
        ipv4_address: 172.26.1.8

  influxdb:
    container_name: influxdb
    image: influxdb:${DOCKER_INFLUXDB_VERSION}
    volumes:
      - influxdb-storage:/var/lib/influxdb2:rw
    env_file:
      - .env
    ports:
      - 8086:${DOCKER_INFLUXDB_INIT_PORT}
    networks:
      metrics:
        ipv4_address: 172.19.1.5

  grafana:
     image: ghcr.io/cueltschey/parkme-grafana
     build:
       context: grafana
     volumes:
       - grafana-storage:/var/lib/grafana:rw
     env_file:
       - .env
     ports:
       - 3300:${GRAFANA_PORT}
     networks:
       metrics:
         ipv4_address: 172.19.1.6
     depends_on:
       - influxdb




configs:
  unilidar.yml:
    file: ${UNILIDAR_CONFIG:-configs/replay2.yaml}

networks:
  default:
    driver: bridge

  pointcloud:
    name: parkme_pointcloud
    ipam:
      driver: default
      config:
        - subnet: 172.26.1.0/24
  metrics:
    name: rt_metrics
    ipam:
      driver: default
      config:
        - subnet: 172.19.1.0/24

volumes:
  influxdb-storage:
  grafana-storage:
