{
 "title": "sni5gect",
 "description": "A dashboard for visualizing the results of sniffing with sni5gect",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Master Information Block",
   "type": "table",
   "description": "PBCH MIB recieved from the gNB",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"rtusystem\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"mib\"\n  ) \n  |> drop(columns: [\"_start\", \"_stop\"])\n  |> pivot(\n    rowKey:[\"_time\"],\n    columnKey: [\"_field\"],\n    valueColumn: \"_value\"\n  )"
    }
   ]
  },
  {
   "title": "Band Info",
   "type": "table",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 5 },
   "targets": [
    {
     "query": "from(bucket: \"rtusystem\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"band_report\"\n  ) \n  |> drop(columns: [\"_start\", \"_stop\", \"sni5gect_data_id\"])\n  |> pivot(\n    rowKey:[\"_time\"],\n    columnKey: [\"_field\"],\n    valueColumn: \"_value\"\n  )"
    }
   ]
  },
  {
   "title": "Channel Configuration",
   "type": "table",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {
     "query": "from(bucket: \"rtusystem\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"channel_config\"\n  ) \n  |> drop(columns: [\"_start\", \"_stop\", \"sni5gect_data_id\"])\n  |> pivot(\n    rowKey:[\"_time\"],\n    columnKey: [\"_field\"],\n    valueColumn: \"_value\"\n  )"
    }
   ]
  },
  {
   "title": "PRACH Configuration",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 15 },
   "targets": [
    {
     "query": "from(bucket: \"rtusystem\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"prach_cfg\"\n  ) \n  |> drop(columns: [\"_start\", \"_stop\", \"sni5gect_data_id\"])\n  |> pivot(\n    rowKey:[\"_time\"],\n    columnKey: [\"_field\"],\n    valueColumn: \"_value\"\n  )"
    }
   ]
  }
 ]
}